[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[window]
opacity = 0.97

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"